server:
  port: 8090

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userAuthenticationDetails?createDatabaseIfNotExist=true
    username: root
    password: toor1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka